"""add assessment records table

Revision ID: 0866c53fd3e8
Revises: 0bd3bd9ca416
Create Date: 2026-09-11 12:51:00.456866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0866c53fd3e8'
down_revision: Union[str, Sequence[str], None] = '0bd3bd9ca416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('legal_knowledge_source_key', sa.String(length=128), nullable=False),
    sa.Column('facts_json', sa.Text(), nullable=False),
    sa.Column('classification_json', sa.Text(), nullable=False),
    sa.Column('obligations_json', sa.Text(), nullable=False),
    sa.Column('evidence_assessments_json', sa.Text(), nullable=False),
    sa.Column('gaps_json', sa.Text(), nullable=False),
    sa.Column('review_flags_json', sa.Text(), nullable=False),
    sa.Column('llm_calls_json', sa.Text(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_records')
    # ### end Alembic commands ###
