"""initial legal knowledge schema

Revision ID: 0bd3bd9ca416
Revises: 
Create Date: 2026-09-09 23:18:02.004825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd3bd9ca416'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('celex_id', sa.String(length=32), nullable=False),
    sa.Column('official_title', sa.Text(), nullable=False),
    sa.Column('oj_reference', sa.String(length=128), nullable=False),
    sa.Column('date_of_act', sa.Date(), nullable=False),
    sa.Column('date_published', sa.Date(), nullable=False),
    sa.Column('date_entry_into_force', sa.Date(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_fetch_sha256', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_table('legal_provisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('citation', sa.String(length=128), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['legal_provisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citation', 'version', name='uq_provision_citation_version')
    )
    op.create_table('provenance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('SOURCE_DOCUMENT', 'PROVISION', 'REQUIREMENT', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('retrieval_method', sa.Enum('MANUAL', 'AUTOMATED', name='retrievalmethod'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_key', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('primary_provision_id', sa.String(length=36), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_provision_id'], ['legal_provisions.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_key', 'version', name='uq_requirement_key_version')
    )
    op.create_table('applicability_conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('actor_role', sa.Enum('PROVIDER', 'DEPLOYER', 'IMPORTER', 'DISTRIBUTOR', 'ANY', name='actorrole'), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('annex_iii_category', sa.String(length=8), nullable=True),
    sa.Column('temporal_start', sa.Date(), nullable=False),
    sa.Column('temporal_end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_provision_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['source_provision_id'], ['legal_provisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exceptions')
    op.drop_table('applicability_conditions')
    op.drop_table('requirements')
    op.drop_table('provenance_records')
    op.drop_table('legal_provisions')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
