"""add framework crosswalks table

Revision ID: 52238527c822
Revises: 0866c53fd3e8
Create Date: 2026-09-12 11:32:26.717485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52238527c822'
down_revision: Union[str, Sequence[str], None] = '0866c53fd3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework_crosswalks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('framework_name', sa.String(length=64), nullable=False),
    sa.Column('citation', sa.String(length=64), nullable=False),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_crosswalks')
    # ### end Alembic commands ###
