"""add ai systems table and assessment fk

Revision ID: 7ecb24681876
Revises: 52238527c822
Create Date: 2026-09-12 11:53:08.615406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ecb24681876'
down_revision: Union[str, Sequence[str], None] = '52238527c822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # batch mode: SQLite has no ALTER TABLE ADD CONSTRAINT, so adding a FK-backed column
    # needs the copy-and-move strategy instead of a bare add_column + create_foreign_key.
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_system_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_assessment_records_ai_system_id', 'ai_systems', ['ai_system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assessment_records_ai_system_id', type_='foreignkey')
        batch_op.drop_column('ai_system_id')
    op.drop_table('ai_systems')
    # ### end Alembic commands ###
