"""add tenants, users, and tenant scoping

Revision ID: b4e1c7a92f30
Revises: d6fd90069446
Create Date: 2026-09-13 09:40:00.000000

Hand-written rather than autogenerated: the schema change is the easy half, and the data
backfill is the half that matters. Existing installs have rows with no tenant -- either a
NULL tenant_id (ai_systems, assessment_records, where the column existed but was unused)
or no column at all (incidents). Those rows have to land in a real tenant before the
column can go NOT NULL, or the migration fails on any non-empty database.

So: create a "Default Tenant", adopt every existing row into it, and only then tighten the
constraint. Incidents inherit their tenant from the AI system they belong to, which is the
only correct source -- an incident is not independently owned.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4e1c7a92f30"
down_revision: Union[str, Sequence[str], None] = "d6fd90069446"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed rather than random so the migration is reproducible and the row is recognisable
# in a support conversation ("is your data still on the default tenant?").
DEFAULT_TENANT_ID = "00000000-0000-0000-0000-000000000001"
DEFAULT_TENANT_NAME = "Default Tenant"


def upgrade() -> None:
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "MEMBER", "VIEWER", name="userrole"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_user_email"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"])

    # Adopt pre-tenancy data. Runs unconditionally: inserting the tenant row on an empty
    # database is harmless and keeps a fresh install consistent with an upgraded one.
    op.execute(
        sa.text(
            "INSERT INTO tenants (id, name, created_at) "
            "VALUES (:id, :name, CURRENT_TIMESTAMP)"
        ).bindparams(id=DEFAULT_TENANT_ID, name=DEFAULT_TENANT_NAME)
    )
    for table in ("ai_systems", "assessment_records"):
        op.execute(
            sa.text(
                f"UPDATE {table} SET tenant_id = :tid WHERE tenant_id IS NULL"
            ).bindparams(tid=DEFAULT_TENANT_ID)
        )

    # incidents never had the column; derive it from the owning system so an incident can
    # never end up in a different tenant than its AI system.
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tenant_id", sa.String(length=36), nullable=True))
    op.execute(
        sa.text(
            "UPDATE incidents SET tenant_id = "
            "(SELECT ai_systems.tenant_id FROM ai_systems WHERE ai_systems.id = incidents.ai_system_id)"
        )
    )
    # Belt and braces: an orphaned incident (no matching system) would still be NULL, and
    # must not block the NOT NULL below.
    op.execute(
        sa.text("UPDATE incidents SET tenant_id = :tid WHERE tenant_id IS NULL").bindparams(
            tid=DEFAULT_TENANT_ID
        )
    )

    # Now every row has a tenant, so the constraint can be enforced. Batch mode because
    # SQLite cannot ALTER a column in place.
    with op.batch_alter_table("ai_systems", schema=None) as batch_op:
        batch_op.alter_column(
            "tenant_id",
            existing_type=sa.String(length=128),
            type_=sa.String(length=36),
            nullable=False,
        )
        batch_op.create_index(op.f("ix_ai_systems_tenant_id"), ["tenant_id"])
    with op.batch_alter_table("assessment_records", schema=None) as batch_op:
        batch_op.alter_column(
            "tenant_id",
            existing_type=sa.String(length=128),
            type_=sa.String(length=36),
            nullable=False,
        )
        batch_op.create_index(op.f("ix_assessment_records_tenant_id"), ["tenant_id"])
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.alter_column(
            "tenant_id", existing_type=sa.String(length=36), nullable=False
        )
        batch_op.create_index(op.f("ix_incidents_tenant_id"), ["tenant_id"])


def downgrade() -> None:
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(op.f("ix_incidents_tenant_id"))
        batch_op.drop_column("tenant_id")
    with op.batch_alter_table("assessment_records", schema=None) as batch_op:
        batch_op.drop_index(op.f("ix_assessment_records_tenant_id"))
        batch_op.alter_column(
            "tenant_id",
            existing_type=sa.String(length=36),
            type_=sa.String(length=128),
            nullable=True,
        )
    with op.batch_alter_table("ai_systems", schema=None) as batch_op:
        batch_op.drop_index(op.f("ix_ai_systems_tenant_id"))
        batch_op.alter_column(
            "tenant_id",
            existing_type=sa.String(length=36),
            type_=sa.String(length=128),
            nullable=True,
        )
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")
