"""add incidents table

Revision ID: d6fd90069446
Revises: 7ecb24681876
Create Date: 2026-09-12 15:12:17.918290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fd90069446'
down_revision: Union[str, Sequence[str], None] = '7ecb24681876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_system_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Enum('DEATH_OR_SERIOUS_HEALTH_HARM', 'CRITICAL_INFRASTRUCTURE_DISRUPTION', 'FUNDAMENTAL_RIGHTS_INFRINGEMENT', 'PROPERTY_OR_ENVIRONMENT_HARM', 'WIDESPREAD_INFRINGEMENT', name='incidentseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
